Added some languages
Nemu627/Hello-World pull request #14
Opened 2022-03-15 14:47 UTC by tubuanha

2022-03-15 15:32 UTC, Googlefan256 commented
I think PowerShell might be same as shell script.

2022-03-15 22:01 UTC, sevenc-nanashi requested changes

2022-03-15 22:01 UTC, sevenc-nanashi commented on PowerShell/Hello-World.ps1
> +echo "Hello, World!"
```suggestion
Write-Output "Hello, World!"
```
I think it should use full name of command let

2022-03-16 02:49 UTC, waki285 requested changes

2022-03-16 02:49 UTC, waki285 commented on Emojicode/Hello-World.emojic
> +  😀 🔤Hello, Emojicode!🔤 ❗
```suggestion
  😀 🔤Hello, World!🔤 ❗
```
It maybe Paru.

2022-03-16 10:08 UTC, Nemu627 commented
Hello. Thanks for the pull request.
I have confirmed that all languages except Hodor work correctly.
Please wait a while longer.

2022-03-18 11:13 UTC, Nemu627 commented
Confirmation of Hodor was made.
When executed, the output string was "Hello world!".
It is necessary to output "Hello, World!" instead of "Hello world!".
Thank you in advance for your help.

2022-03-19 08:03 UTC, tubuanha commented
Thank you very much.
I have made the correction and would appreciate your confirmation.

2022-03-19 08:35 UTC, Nemu627 commented
It's been verified to work correctly in all languages!
Thanks for the great request!

2022-03-19 08:35 UTC, merged